/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CloxClient.java
 *
 * Created on May 13, 2009, 9:45:19 PM
 */
package com.trinisoft.cloxclient.ui;

import com.trinisoft.cloxclient.Client;
import com.trinisoft.cloxclient.handlers.Messenger;
import com.trinisoft.cloxclient.models.Message;
import com.trinisoft.cloxclient.models.Messages;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import javax.swing.AbstractListModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;

/**
 *
 * @author segun
 */
public class CloxClient extends javax.swing.JFrame {

    Client client;
    String username;
    public int[] selectedClients;
    public Object[] names;

    /** Creates new form CloxClient */
    public CloxClient() {
        initComponents();
        selectedClients = new int[0];
        //txtRecieved.setContentType("text/html");
    }

    public void setNames(final Object[] names) {
        this.names = names;
        namesList.setModel(new AbstractListModel() {

            Object myNames[] = names;

            public int getSize() {
                return myNames.length;
            }

            public Object getElementAt(int index) {
                return myNames[index];
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();
        scroller = new javax.swing.JScrollPane();
        messageList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        btnSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        namesList = new javax.swing.JList();
        lblStatus = new javax.swing.JLabel();
        chkAll = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        btnSendFile = new javax.swing.JButton();
        btnDisconnect1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtToSend = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Username:");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.setSelected(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnDisconnect.setText("Disconnect");
        btnDisconnect.setEnabled(false);
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnDisconnect, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnDisconnect))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        scroller.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        scroller.setViewportView(messageList);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSend.setText("Send");
        btnSend.setEnabled(false);
        btnSend.setSelected(true);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        namesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namesListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(namesList);

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStatus.setText("Disconnected");
        lblStatus.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        chkAll.setText("    Everyone");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnSendFile.setText("Send File");
        btnSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFileActionPerformed(evt);
            }
        });

        btnDisconnect1.setText("Send SMS");
        btnDisconnect1.setEnabled(false);
        btnDisconnect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnect1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnSendFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDisconnect1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendFile)
                    .addComponent(btnDisconnect1))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBar(null);

        txtToSend.setColumns(20);
        txtToSend.setLineWrap(true);
        txtToSend.setRows(5);
        txtToSend.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtToSendCaretPositionChanged(evt);
            }
        });
        txtToSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtToSendKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtToSend);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scroller, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scroller, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkAll)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        final CloxClient cloxClient = this;
        btnLogin.setEnabled(false);
        new Thread() {

            public void run() {
                if (!Client.STOP_CLIENT) {
                    Client.STOP_CLIENT = true;
                    try {
                        Thread.sleep(3000);
                    } catch (InterruptedException ie) {
                        ie.printStackTrace();
                    }
                }
                if (!txtUsername.getText().equals("")) {
                    username = txtUsername.getText();
                    try {
                        client = new Client(username, cloxClient);
                        client.start();
                    } catch (IOException ioe) {
                        ioe.printStackTrace();
                        btnLogin.setEnabled(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(cloxClient, "Please enter a username");
                    btnLogin.setEnabled(true);
                }
            }
        }.start();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        // TODO add your handling code here:
        try {
            client.clientSocket.close();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
}//GEN-LAST:event_btnDisconnectActionPerformed

    private void namesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namesListMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            selectedClients = namesList.getSelectedIndices();
        }
    }//GEN-LAST:event_namesListMouseClicked

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        final CloxClient cloxClient = this;
        btnSend.setEnabled(false);
        new Thread() {

            public void run() {
                Object selectedNames[] = namesList.getSelectedValues();
                Object sendTo[] = new Object[0];
                if (!txtToSend.getText().equals("")) {
                    if (chkAll.isSelected()) {
                        int option = JOptionPane.showConfirmDialog(cloxClient, "Are you sure you want to send this message to everyone?", "Clox Client: Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
                        if (option == JOptionPane.YES_OPTION) {
                            sendTo = names;
                        } else {
                            btnSend.setEnabled(true);
                            return;
                        }
                    } else {
                        sendTo = selectedNames;
                    }
                    if (sendTo.length <= 0) {
                        JOptionPane.showMessageDialog(cloxClient, "Please select a user.", "Clox Client: Message", JOptionPane.ERROR_MESSAGE);
                        btnSend.setEnabled(true);
                        return;
                    }
                    for (Object to : sendTo) {
                        Message message = Messenger.produceMessage(txtToSend.getText(), username, to.toString(), new Date());
                        Messenger.sendMessage(message, client.clientSocket);
                        Messages.list.add(message);
                        messageList.setCellRenderer(new ListCellRenderer() {

                            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                                return new JLabel(value.toString());
                            }
                        });
                        
                        messageList.setModel(new HTMLListModel(Messages.list));
                        messageList.ensureIndexIsVisible(Messages.list.size() - 1);
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ie) {
                            ie.printStackTrace();
                        }
                    }
                    txtToSend.setText("");
                } else {
                    JOptionPane.showMessageDialog(cloxClient, "Please type a message", "Clox Client: Message", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.start();
    }//GEN-LAST:event_btnSendActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
        btnLoginActionPerformed(evt);
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFileActionPerformed
        // TODO add your handling code here:
        btnSend.setEnabled(false);
        Object selectedNames[] = namesList.getSelectedValues();
        Object sendTo[] = new Object[0];

        if (chkAll.isSelected()) {
            int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to send this message to everyone?", "Clox Client: Confirm", JOptionPane.YES_NO_CANCEL_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                sendTo = names;
            } else {
                btnSendFile.setEnabled(true);
                return;
            }
        } else {
            sendTo = selectedNames;
        }
        if (sendTo.length <= 0) {
            JOptionPane.showMessageDialog(this, "Please select a user.", "Clox Client: Message", JOptionPane.ERROR_MESSAGE);
            btnSendFile.setEnabled(true);
            return;
        }
        JFileChooser jFileChooser = new JFileChooser();
        int retVal = jFileChooser.showOpenDialog(this);
        if (retVal == JFileChooser.APPROVE_OPTION) {
            File f = jFileChooser.getSelectedFile();
            //Messenger.sendFile(f, client.clientSocket);
            for (Object to : sendTo) {
                Messenger.sendFile(f, client.clientSocket, to.toString());
            }
        }
}//GEN-LAST:event_btnSendFileActionPerformed

    private void btnDisconnect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisconnect1ActionPerformed

    private void txtToSendKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToSendKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() != KeyEvent.VK_ENTER) {
            if (txtToSend.getText().equals("")) {
                btnSend.setEnabled(false);
            } else {
                btnSend.setEnabled(true);
            }
        } else {
            btnSendActionPerformed(null);           
        }
}//GEN-LAST:event_txtToSendKeyReleased

    private void txtToSendCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtToSendCaretPositionChanged
        // TODO add your handling code here:
        if (txtToSend.getText().equals("")) {
            btnSend.setEnabled(false);
        } else {
            btnSend.setEnabled(true);
        }
}//GEN-LAST:event_txtToSendCaretPositionChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CloxClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDisconnect;
    public javax.swing.JButton btnDisconnect1;
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnSend;
    public javax.swing.JButton btnSendFile;
    public javax.swing.JCheckBox chkAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblStatus;
    public javax.swing.JList messageList;
    public javax.swing.JList namesList;
    public javax.swing.JScrollPane scroller;
    private javax.swing.JTextArea txtToSend;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
